### PR TITLE
Adding persian language.

### PR DESCRIPTION
**Pull request by BaseMax**
Hi,

**Target:** Persian, also known by its endonym Farsi (فارسی)
New documentation file created.
Soon it will be completed by our team.

Regards,
Max

### CODE REVIEW

**Comment by Maikuolan** [comment]
Thank you for your contribution to the project. It is greatly appreciated. :-)

I'll send you an invite now.

**Comment by Maikuolan** [comment]
Hi @BaseMax. Any further progress on this? :-)

**Comment by BaseMax** [comment]
Hello @Maikuolan,

Sorry, We will inform you about the new updates in next weeks.

Best,
Max

**Comment by Maikuolan** [comment]
I'll be making some big changes to the documentation very soon, and when that happens, it will be easier to just start fresh, rather than trying to sync up from all the changed parts of the original. Seeing as this pull request hasn't seen any activity at all in more than a year now, and is already outdated, I'll go ahead and close it now. If anyone wants to try the translation again, they're welcome to do so, and a new pull request can be opened. Thanks. :-)

**Comment by BaseMax** [comment]
Hello @Maikuolan,

Thanks for your message, and sorry for this.
I will continue this, What time you update documentation?
I want to see new changes and apply...
Of course, I will help in my free time.

Regards,
Max Base

**Comment by Maikuolan** [comment]
Thank you; I appreciate the help. :-)

> What time you update documentation?

I'm currently working towards completing v3, which will introduce some significant changes to phpMussel, and I'll need to update the documentation according to those changes. So, v3 will come first, and that may require a few days, but I should be able to finish the changes to the documentation shortly after that. I imagine everything taking about a week to finish (but, I'm also doing it all in my spare time too, so it will also depend on whether anything unexpected happens during the week, whether there are changes to my schedule, etc, so it should be regarded as a very rough estimate).

**Comment by BaseMax** [comment]
Hello Caleb,
Is everything going well? @Maikuolan 

I follow the commits:
https://github.com/phpMussel/Docs/commits/master

**Comment by Maikuolan** [comment]
Hi @BaseMax,

Thank you for asking. :-)

Progress has been a little slower than I would like, due to various distractions, other commitments, etc. There are still many things that I need to finish translating for the existing translations, and there are still some new things that I hope to eventually add to the documentation. But, I've finished removing all outdated content which isn't relevant anymore since v3 onward, so that anything currently in the documentation currently should be still be relevant for the current major version.

It should be okay to start working on some new Farsi/Persian translations now, if you want to do so (and also, thank you again for the help). For the remaining things that I still hope to eventually add, I can always just add them in later, I guess (their absence right now, shouldn't prevent new work being done, and shouldn't cause any problems, I think), and anyway, since the outdated material has been removed now, any new translations done won't be wasted, I think.

**Comment by Maikuolan** [comment]
Something to note: You may notice that currently, there isn't any section 5 or section 6 (section 4 continuing immediately onto section 7). Not exactly a mistake. There was content there, from the previous major version, which I removed. But, I decided to not renumber all the sections, because I figured that some of the new things that I hope to eventually add to the documentation could go there (since, if I don't need to renumber all the sections from 7 onward, it means a little less work). ;-)

Aside from that, I hope to eventually add some new FAQ entries. But, everything else is finished and ready for translation. :-)

**Comment by Maikuolan** [comment]
BTW, @BaseMax, would you be interested in localisation for the phpMussel codebase? If not, no problem, no worries. But, I just thought, I should ask, because that would be something really cool, too. :-)

The main L10N data for v3 (I wouldn't worry about previous major versions anymore, i.e., v2, v1, v0) is shared across 5 different repositories: Core (53 strings), FrontEnd (266 strings), Web (21 strings), CLI (12 strings), and Plugin-PHPMailer (16 strings). (Many of the FrontEnd strings simply describe some of the available configuration options, so can safely be copy/pasted to the descriptions of configuration options provided by the documentation, since they're the same).

https://github.com/phpMussel/Core/tree/v3/l10n
https://github.com/phpMussel/FrontEnd/tree/v3/l10n
https://github.com/phpMussel/Web/tree/v3/l10n
https://github.com/phpMussel/CLI/tree/v3/src
https://github.com/phpMussel/Plugin-PHPMailer/tree/v3/l10n

**Comment by Maikuolan** [comment]
Persian/Farsi L10N for the [Core](https://github.com/phpMussel/Core/blob/v3/l10n/fa.yml), [Web](https://github.com/phpMussel/Web/blob/v3/l10n/fa.yml), [CLI](https://github.com/phpMussel/CLI/blob/v3/l10n/fa.yml), and [PHPMailer-Linker](https://github.com/phpMussel/Plugin-PHPMailer/blob/v3/l10n/fa.yml) packages has been completed. Persian/Farsi L10N for the FrontEnd package is still a work-in-progress, but I anticipate completing it soon (probably a week or so thereabouts). Because my knowledge of Persian/Farsi is *very* limited, and I rely on machine translation, there'll likely be numerous errors. If anyone wants to send some pull requests with corrections, that would be welcomed. Otherwise though, if not interested, no problem. It'll do for now. :-)

**Comment by BaseMax** [comment]
> Because my knowledge of Persian/Farsi is very limited.

ah Nice, Really?

I remember I translated half of the old version. So If you updated that. I need to again look at and rewrite it.
If I find time, I would like to help.

**Comment by BaseMax** [comment]
https://github.com/phpMussel/Plugin-PHPMailer/blob/v3/l10n/fa.yml

Wow, can you read and type in Persian?

I am a Persian native man. Don't worry, I'm here to help.

**Comment by Maikuolan** [comment]
> can you read and type in Persian?

Reading and typing? Yes. But, actually understanding it? Just a little, and not very well. So, I'm happy to try it, but my confidence is very low. '^^

> I am a Persian native man. Don't worry, I'm here to help.

Awesome. Very much appreciated. :-)

**Comment by BaseMax** [comment]
Great, really amazing. I was surprised.

Please let me know which files are ready to review. I would like to check, review and improve these if there is anything incomplete. 

I waiting for that.

**Comment by Maikuolan** [comment]
> I remember I translated half of the old version. So If you updated that. I need to again look at and rewrite it.
> If I find time, I would like to help.

That would be fantastic. :-)

Currently, what exists in the documentation is up to-date, but I've been intending to write some guidelines for users regarding how to migrate to v3 from older versions, which I'll create a new section for in the README later, but haven't found sufficient time to write yet. So, there's still a little work still for me to do at the READMEs in that regard. But, aside from the migration guidelines, everything else in the documentation should be okay to translate now. :-)

> Please let me know which files are ready to review. I would like to check, review and improve these if there is anything incomplete.
>
> I waiting for that.

Excellent; will do. :+1:

**Comment by BaseMax** [comment]
That is great. I'm waiting for it.

P.S: I have something to talk about. It's possible to contact you via your email address? I cannot find your email.

**Comment by Maikuolan** [comment]
> It's possible to contact you via your email address? I cannot find your email.

No problem. You can email me via my username here (at) gmail (dot) com. :-)

**Comment by Maikuolan** [comment]
For the "Core" repository: https://github.com/phpMussel/Core/blob/v3/l10n/fa.yml
For the "Web" repository: https://github.com/phpMussel/Web/blob/v3/l10n/fa.yml
For the "CLI" repository: https://github.com/phpMussel/CLI/blob/v3/l10n/fa.yml
For the "Plugin-PHPMailer" repository: https://github.com/phpMussel/Plugin-PHPMailer/blob/v3/l10n/fa.yml
Latest version of the documentation (used my "DocGen" script to automatically import some of the incomplete "FrontEnd" L10N strings into the documentation where they would appear at the configuration section, but aside from that, untouched): https://github.com/phpMussel/Docs/blob/fa-docgen-wip/readme.fa.md
And for the "FrontEnd" repository: Not yet committed due to currently working on it tonight, but I'll commit that very soon (and will post a link here as soon as committed).

:-)

**Comment by Maikuolan** [comment]
> And for the "FrontEnd" repository: Not yet committed due to currently working on it tonight, but I'll commit that very soon (and will post a link here as soon as committed).

Has now been committed: https://github.com/phpMussel/FrontEnd/blob/v3/l10n/fa.yml

**Comment by BaseMax** [comment]
Hey Caleb.

Hopefully, I will review the files this week just before ending October. I will report it here.

Cheers

**Pull request closed without merging**
